version: '3'

services:
  app:
    entrypoint: [bin/start]
    image: gd2l/greenlight:v2
    container_name: greenlight-v2
    build:
          context: ./
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
# When using external logging
#    logging:
#      driver: $LOG_DRIVER
#      options:
#        syslog-address: $LOG_ADDRESS
#        tag: $LOG_TAG
    volumes:
      - ./log:/usr/src/app/log
# When using sqlite3 as the database
#      - ./db/production:/usr/src/app/db/production
# When using postgresql as the database
    links:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.238.2

  db:
    image: postgres:9.5
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/production:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      app_net:
        ipv4_address: 172.16.238.3

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
